REM Copy Source
SET mdlName1=HighClearance_model

REM Autogenerated files and paths based on model's name
SET srcPath1=Work\%mdlName1%_ert_rtw\
SET srcFile1=%srcPath1%%mdlName1%.c
SET srcFile2=%srcPath1%%mdlName1%.h
REM List of path\files to be copied
REM SET srcList=%srcFile1% %srcFile2% %srcFile3% %srcFile4%
REM Destination path
SET destPath=Gen\

REM FOR %I IN (%srcList%) DO copy /Y %I %destPath%

copy /Y %srcFile1% %destPath%
copy /Y %srcFile2% %destPath%
