/**
*  @file   Project.h
*
*  @brief	Interface header between project and the single modules.
*
*/

#ifndef __PROJECT_H
#define __PROJECT_H

#include "util_eosGd.h"				// Utility header file for eos and gd

#include "Eemm.h"					// Header containing error management defines
#include "Eemm_Gd.h"				// Header containing error management defines for GD interface

#include "Gd_Ids/RGCH2_Gd_Ln.h"		// Project specific header file containing the complete list of the project specific GD-nodes
#include "Gd_Ids/RGCH2_Gd_Id.h"		// Project specific header file containing the complete list of the project specific GD-indices
#include "Gd_Mapping.h"				// Project specific header file which maps the module GD-indices/nodes to the project GD-indices/nodes
#include "Chassis_IO.h"				// Project specific header file containing the mapping of the module IO names vs. the project IO defines (autogenerated)
#include "Eeprom.h"					// Project specific header file containing the start addresses of the different EEPROM blocks
#include "HC.h"						// Project specific header file containing defines needed for high clearance
#include "EEMM_PRJ.h"				// Project specific header file containing defines needed for external error managament

#include "..\..\ExternalLinks\Parts_Store\Chassis\Chassis_Functions\Control_Logic\High_Clearance\Src\HC_GD_ID.h"

#endif // __PROJECT_H
