/*
 *  @Copyright: AGCO Corporation
 *  
 *  @File: C:\Dev\Chassis_Development\RGCH2\ExternalLinks\Parts_Store\Chassis\Chassis_Functions\Control_Logic\High_Clearance\src\HC_GD_ID.h
 *
 *  @Machine Variant: 
 *
 *  This as an AutoGenerated file from: GD_ID_HC.xlsm
 *
 *  Generated on: 2018/12/7 8:13:16 AM
 *
 *  Do NOT modify this source file
 */

#ifndef __HC_GD_ID_H 
    #define __HC_GD_ID_H

enum
{

 /* ================================================================================================================================================================== 
    High Clearance Module (HC)
    Logical Node:  54 (0x36)
    Physical Node: 4 (0x4)
    ID-Range:      0x6C00 - 0x6DFF
    ================================================================================================================================================================== 
    Variable name                                                                      Index             Status     Range     Scaling Unit                Description */
    GD_ID_HC_TARGET_STATE                                                            = 0x6C00, // 27648  1/0        0..6      1       enum                Data, Target state for control. Status, Control is enabled
    GD_ID_HC_MACHINE_STATE                                                           = 0x6C01, // 27649  1/0        0..6      1       enum                Data, Actual state of machine. Status, Control is active
    GD_ID_HC_LEG_STATE_FRONTLEFT                                                     = 0x6C02, // 27650  ---        0..6      1       enum                Actual state of leg
    GD_ID_HC_LEG_STATE_FRONTRIGHT                                                    = 0x6C03, // 27651  ---        0..6      1       enum                Actual state of leg
    GD_ID_HC_LEG_STATE_REARLEFT                                                      = 0x6C04, // 27652  ---        0..6      1       enum                Actual state of leg
    GD_ID_HC_LEG_STATE_REARRIGHT                                                     = 0x6C05, // 27653  ---        0..6      1       enum                Actual state of leg
    GD_ID_HC_TARGET_CLEARANCE_FL                                                     = 0x6C06, // 27654  ---        0..2000   1       mm                  Target clearance height for leg
    GD_ID_HC_TARGET_CLEARANCE_FR                                                     = 0x6C07, // 27655  ---        0..2000   1       mm                  Target clearance height for leg
    GD_ID_HC_TARGET_CLEARANCE_RL                                                     = 0x6C08, // 27656  ---        0..2000   1       mm                  Target clearance height for leg
    GD_ID_HC_TARGET_CLEARANCE_RR                                                     = 0x6C09, // 27657  ---        0..2000   1       mm                  Target clearance height for leg

    GD_ID_HC_ACTUAL_CLEARANCE_FL                                                     = 0x6C0A, // 27658  1/0        0..2000   1       mm                  Data, Actual clearance height for leg. Status, Leg control is enabled
    GD_ID_HC_ACTUAL_CLEARANCE_FR                                                     = 0x6C0B, // 27659  1/0        0..2000   1       mm                  Data, Actual clearance height for leg. Status, Leg control is enabled
    GD_ID_HC_ACTUAL_CLEARANCE_RL                                                     = 0x6C0C, // 27660  1/0        0..2000   1       mm                  Data, Actual clearance height for leg. Status, Leg control is enabled
    GD_ID_HC_ACTUAL_CLEARANCE_RR                                                     = 0x6C0D, // 27661  1/0        0..2000   1       mm                  Data, Actual clearance height for leg. Status, Leg control is enabled
    GD_ID_HC_STROKE_LEGNTH_RAW_FL                                                    = 0x6C0E, // 27662  ---        0..2000   1       mm                  Raw length cylinder is extended
    GD_ID_HC_STROKE_LEGNTH_RAW_FR                                                    = 0x6C0F, // 27663  ---        0..2000   1       mm                  Raw length cylinder is extended
    GD_ID_HC_STROKE_LEGNTH_RAW_RL                                                    = 0x6C10, // 27664  ---        0..2000   1       mm                  Raw length cylinder is extended
    GD_ID_HC_STROKE_LEGNTH_RAW_RR                                                    = 0x6C11, // 27665  ---        0..2000   1       mm                  Raw length cylinder is extended
    GD_ID_HC_OKAY_TO_TRANSITION                                                      = 0x6C12, // 27666  ---        0..3      1       bitfield            Indicates if settings are sutible for raising and lowering
    GD_ID_HC_CYLINDER_PWM_EXTEND_FL                                                  = 0x6C13, // 27667  ---        0..100    1       %                   Dutycycle pct for cylinder

    GD_ID_HC_CYLINDER_PWM_EXTEND_FR                                                  = 0x6C14, // 27668  ---        0..100    1       %                   Dutycycle pct for cylinder
    GD_ID_HC_CYLINDER_PWM_EXTEND_RL                                                  = 0x6C15, // 27669  ---        0..100    1       %                   Dutycycle pct for cylinder
    GD_ID_HC_CYLINDER_PWM_EXTEND_RR                                                  = 0x6C16, // 27670  ---        0..100    1       %                   Dutycycle pct for cylinder
    GD_ID_HC_CYLINDER_PWM_RETRCT_FL                                                  = 0x6C17, // 27671  ---        0..100    1       %                   Dutycycle pct for cylinder
    GD_ID_HC_CYLINDER_PWM_RETRCT_FR                                                  = 0x6C18, // 27672  ---        0..100    1       %                   Dutycycle pct for cylinder
    GD_ID_HC_CYLINDER_PWM_RETRCT_RL                                                  = 0x6C19, // 27673  ---        0..100    1       %                   Dutycycle pct for cylinder
    GD_ID_HC_CYLINDER_PWM_RETRCT_RR                                                  = 0x6C1A, // 27674  ---        0..100    1       %                   Dutycycle pct for cylinder
    GD_ID_HC_LADDER_EXTEND                                                           = 0x6C1B, // 27675  1/0        0..0      1                           Command to extend ladder
    GD_ID_HC_REQUEST_CCO_OFF                                                         = 0x6C1C, // 27676  1/0        0..0      1                           Request to kill enable for hydrualic power
    GD_ID_HC_USER_WARNINGS                                                           = 0x6C1D, // 27677  ---        0..255    1       bitfield            Induicates which warning(s) is preventing movement

    GD_ID_HC_MOVEMENT_ERROR_FL                                                       = 0x6C22, // 27682  ---        0..7      1       bitfield            Indicates if a movement error happened on a leg
    GD_ID_HC_MOVEMENT_ERROR_FR                                                       = 0x6C1F, // 27679  ---        0..7      1       bitfield            Indicates if a movement error happened on a leg
    GD_ID_HC_MOVEMENT_ERROR_RL                                                       = 0x6C20, // 27680  ---        0..7      1       bitfield            Indicates if a movement error happened on a leg
    GD_ID_HC_MOVEMENT_ERROR_RR                                                       = 0x6C21, // 27681  ---        0..7      1       bitfield            Indicates if a movement error happened on a leg
    GD_ID_HC_MANUAL_OVERRIDE                                                         = 0x6C1E, // 27678  1/0        0..56596  1                           Data - R/W, See definition Doc. Status - R, Manual override active
    GD_ID_HC_CAL_STATE                                                               = 0x6C23, // 27683  1/0        0..65535  1                           Data, See definition Doc. Status, Calibration overriding control
    GD_ID_HC_CAL_CMD                                                                 = 0x6C24, // 27684  ---        0..65535  1                           Data, See definition Doc.
    GD_ID_HC_SENSOR_RAW_FL                                                           = 0x6C25, // 27685  ---        0..22     0.001                       Height cylinder position sensor current
    GD_ID_HC_SENSOR_RAW_FR                                                           = 0x6C26, // 27686  ---        0..22     0.001                       Height cylinder position sensor current
    GD_ID_HC_SENSOR_RAW_RL                                                           = 0x6C27, // 27687  ---        0..22     0.001                       Height cylinder position sensor current

    GD_ID_HC_SENSOR_RAW_RR                                                           = 0x6C28, // 27688  ---        0..22     0.001                       Height cylinder position sensor current
    GD_ID_HC_COIL_RAW_EXTEND_FL                                                      = 0x6C29, // 27689  ---        0..4000   0.1                         Cylinder coil current
    GD_ID_HC_COIL_RAW_RETRCT_FL                                                      = 0x6C2A, // 27690  ---        0..4000   0.1                         Cylinder coil current
    GD_ID_HC_COIL_RAW_EXTEND_FR                                                      = 0x6C2B, // 27691  ---        0..4000   0.1                         Cylinder coil current
    GD_ID_HC_COIL_RAW_RETRCT_FR                                                      = 0x6C2C, // 27692  ---        0..4000   0.1                         Cylinder coil current
    GD_ID_HC_COIL_RAW_EXTEND_RL                                                      = 0x6C2D, // 27693  ---        0..4000   0.1                         Cylinder coil current
    GD_ID_HC_COIL_RAW_RETRCT_RL                                                      = 0x6C2E, // 27694  ---        0..4000   0.1                         Cylinder coil current
    GD_ID_HC_COIL_RAW_EXTEND_RR                                                      = 0x6C2F, // 27695  ---        0..4000   0.1                         Cylinder coil current
    GD_ID_HC_COIL_RAW_RETRCT_RR                                                      = 0x6C30, // 27696  ---        0..4000   0.1                         Cylinder coil current
    GD_ID_HC_STROKE_LEGNTH_FILTER_FL                                                 = 0x6C31, // 27697  1/0        0..2000   1       mm                  Value: Filtered length cylinder is extended. Status: Filter enabled or not

    GD_ID_HC_STROKE_LEGNTH_FILTER_FR                                                 = 0x6C32, // 27698  1/0        0..2000   1       mm                  Value: Filtered length cylinder is extended. Status: Filter enabled or not
    GD_ID_HC_STROKE_LEGNTH_FILTER_RL                                                 = 0x6C33, // 27699  1/0        0..2000   1       mm                  Value: Filtered length cylinder is extended. Status: Filter enabled or not
    GD_ID_HC_STROKE_LEGNTH_FILTER_RR                                                 = 0x6C34, // 27700  1/0        0..2000   1       mm                  Value: Filtered length cylinder is extended. Status: Filter enabled or not
    GD_ID_HC_ErrorManagement                                                         = 0x6DEE, // 28142  1/0        0..255                                Return path for fault management (acknowledgment)
    GD_ID_HC_LifeMessage                                                             = 0x6DFF, // 28159  ---        0..65535  1       [ms]                Life message

};

#endif //__HC_GD_ID_H
